import ModalLayout from "@/layouts/modal-layout";
import Head from "next/head";
import { useState } from "react";

export default function Home() {
  const [isOpen, setIsOpen] = useState(false);
  return (
    <>
      <Head>
        <title>LA stadium</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div
          className="hero min-h-screen"
          style={{
            backgroundImage: `url("/download.jpg")`,
          }}
        >
          <div className="hero-overlay bg-opacity-60"></div>
          <div className="hero-content text-center text-neutral-content">
            <div className="max-w-md">
              <h1 className="mb-5 text-5xl font-bold">Hello there</h1>
              <p className="mb-5">
                here you add stadium and adjust them set the timer and do alot
                of staff that makes your experience of organizing your field
              </p>
              <button
                className="btn btn-primary"
                onClick={() => setIsOpen(true)}
              >
                Get Started
              </button>
              <ModalLayout
                className="w-[1000px] h-[700px]"
                isOpen={isOpen}
                setIsOpen={setIsOpen}
              >
                <h1 className="text-4xl font-extrabold">test</h1>
                <div className="card w-96 bg-base-100 shadow-xl">
                  <figure className="px-10 pt-10">
                    <img
                      src="/images/stock/photo-1606107557195-0e29a4b5b4aa.jpg"
                      alt="Shoes"
                      className="rounded-xl"
                    />
                  </figure>
                  <div className="card-body items-center text-center ">
                    <h2 className="card-title">Shoes!</h2>
                    <p>If a dog chews shoes whose shoes does he choose?</p>
                    <div className="card-actions">
                      <button className="btn btn-primary">choose</button>
                    </div>
                  </div>
                </div>

                <button
                  className="btn btn-circle absolute bottom-6 bg-center"
                  onClick={() => setIsOpen(false)}
                >
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    className="h-6 w-6"
                    fill="none"
                    viewBox="0 0 24 24"
                    stroke="currentColor"
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      strokeWidth="2"
                      d="M6 18L18 6M6 6l12 12"
                    />
                  </svg>
                </button>
              </ModalLayout>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
