import Head from "next/head";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import axios from "axios";
import { useState } from "react";
import reservationRequestSchema from "@/validation/reservationRequest";

export default function Reservation() {
  const [choosenStadium, setChoosenStadium] = useState(7);

  const {
    register,
    handleSubmit,
    formState: { errors },
    reset,
  } = useForm({
    resolver: zodResolver(reservationRequestSchema),
  });

  const onReserve = async (data) => {
    const res = await axios.post("/api/reservation", {
      stadium: choosenStadium,
      ...data,
    });
    if (res.status === 201) {
      reset();
      setChoosenStadium(7);
    }
  };

  return (
    <>
      <Head>
        <title>LA stadium</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        className="hero min-h-screen"
        style={{
          backgroundImage: `url("/download.jpg")`,
        }}
      >
        <div className="hero-overlay bg-opacity-60"></div>
        <div>
          <h1 className="text-3xl py-4 font-bold mb-6 font text-center underline text-white decoration-lime-500">
            Reservation
          </h1>
          {/* Choose Pitch */}
          <div className="flex justify-center gap-24">
            {/* 10 Persons */}
            <div
              className={
                choosenStadium === 10
                  ? "card w-96 h-[500px] bg-secondary shadow-xl border-4 border-primary"
                  : "card w-96 h-[500px] bg-white shadow-xl"
              }
            >
              <figure className="px-10 pt-10">
                <img src="/terrain.jpg" alt="Shoes" className="rounded-xl" />
              </figure>
              <div className="card-body items-center text-center ">
                <h2 className="card-title">Grand Terrain</h2>
                <p>10 personne par equipe</p>
                <div className="card-actions">
                  <button
                    className="btn btn-primary"
                    onClick={() => setChoosenStadium(10)}
                  >
                    choose
                  </button>
                </div>
              </div>
            </div>
            {/* 7 Persons */}
            <div
              className={
                choosenStadium === 7
                  ? "card w-96 h-[500px] bg-secondary shadow-xl border-4 border-primary"
                  : "card w-96 h-[500px] bg-white shadow-xl"
              }
            >
              <figure className="px-10 pt-10">
                <img
                  src="/terrain.jpg"
                  alt="Shoes"
                  className="rounded-xl w-40 h-60"
                />
              </figure>
              <div className="card-body items-center text-center ">
                <h2 className="card-title pt-9">Petit Terrain</h2>
                <p>7 personne par equipe</p>
                <div className="card-actions">
                  <button
                    className="btn btn-primary"
                    onClick={() => setChoosenStadium(7)}
                  >
                    choose
                  </button>
                </div>
              </div>
            </div>
            <form onSubmit={handleSubmit(onReserve)}>
              {/* Date */}
              <div className=" px-4 py-2 form-control w-full min-w flex item-center">
                <label className="label">
                  <span className="label-text font-semibold text-lg text-white">
                    Date de réservation{" "}
                    <span className="label-text-alt text-red-800 text-lg">
                      *
                    </span>
                  </span>
                </label>
                <input
                  type="date"
                  className="input input-bordered input-primary w-[350px]"
                  {...register("reservationDate", { valueAsDate: true })}
                />
                <p className="text-sm text-red-500 pl-2">
                  {errors.reservationDate?.message}
                </p>
              </div>
              <div className=" px-4 py-2 form-control w-full max-w-lg flex item-center">
                <label className="label">
                  <span className="label-text font-semibold text-lg text-white">
                    Numéro du téléphone{" "}
                    <span className="label-text-alt text-red-800 text-lg">
                      *
                    </span>
                  </span>
                </label>
                <input
                  type="text"
                  placeholder="Entrer votre numéro du téléphone ici..."
                  className="input input-bordered input-primary w-full max-w-lg "
                  {...register("phone")}
                />
                <p className="text-sm text-red-500 pl-2">
                  {errors.phone?.message}
                </p>
              </div>
              <div className="py-8 flex justify-center">
                <button type="submit" className="btn btn-primary">
                  Reserver
                </button>
              </div>
            </form>
          </div>
        </div>
      </main>
    </>
  );
}
