import PlayersInfo from "@/components/tournament/players-info";
import TeamInfo from "@/components/tournament/team-info";
import Head from "next/head";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { tournamentRequestSchema } from "@/validation/tournamentRequest";
import axios from "axios";
export default function Home() {
  const [successMessage, setSuccessMessage] = useState(null);

  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm({
    resolver: zodResolver(tournamentRequestSchema),
  });

  const onSubmit = async (data) => {
    const res = await axios.post("/api/create-user", data);
    if (res.status === 201) {
      reset();
      setSuccessMessage("User created successfully");
    }
  };

  return (
    <>
      <Head>
        <title>LA stadium</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <form>
          <div className="h-screen flex justify-center py-24 gap-16">
            <TeamInfo register={register} errors={errors} />
            <p>{}</p>
            <PlayersInfo />
          </div>
        </form>
      </main>
    </>
  );
}
