import Head from "next/head";

export default function Tournaments() {
  return (
    <>
      <Head>
        <title>LA stadium</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div class="container mx-auto py-10 ">
          <div class="max-w-md mx-auto bg-white p-8 border border-gray-300 rounded-md shadow-md">
            <h2 class="text-2xl font-bold mb-6 font text-center underline decoration-sky-500">
              Formulaire De Tournoi
            </h2>
            <form>
              <div class="mb-4">
                <label
                  for="name"
                  class="block text-gray-700 font-medium mb-2 text-center"
                >
                  Nom D'Equipe
                </label>
                <div class="mt-1 relative rounded-md shadow-sm">
                  <input
                    type="text"
                    id="Nom D'Equipe"
                    name="name"
                    placeholder="Enter your name"
                    class="w-full px-4 py-2 rounded-md border-gray-300 focus:outline-none focus:border-blue-500 text-center"
                    required
                  />
                </div>
              </div>
              <div class="mb-4">
                <label for="name" class="block text-gray-700 font-medium mb-2">
                  Nom Du Capitain
                </label>
                <div class="mt-1 relative rounded-md shadow-sm">
                  <input
                    type="text"
                    id="Nom D'Equipe"
                    name="name"
                    placeholder="Enter your name"
                    class="w-full px-4 py-2 rounded-md border-gray-300 focus:outline-none focus:border-blue-500"
                    required
                  />
                </div>
              </div>
              <div class="mt-4">
                <label
                  for="phone"
                  class="block text-sm font-medium text-gray-700"
                >
                  Phone Number
                </label>
                <div class="mt-1 relative rounded-md shadow-sm">
                  <input
                    type="text"
                    name="phone"
                    id="phone"
                    class="w-full px-4 py-2 rounded-md border-gray-300 focus:outline-none focus:border-blue-500 "
                    placeholder="Enter your phone number"
                  />
                  <div class="absolute inset-y-0 right-0 pr-3 flex items-center pointer-events-none">
                    <span class="text-gray-500 sm:text-sm"> 8 digits </span>
                  </div>
                </div>
              </div>

              <div class="mb-4">
                <label for="name" class="block text-gray-700 font-medium mb-2">
                  Joueur0
                </label>
                <div class="mt-1 relative rounded-md shadow-sm">
                  <input
                    type="text"
                    id="Joueur0"
                    name="name"
                    placeholder="Enter the name"
                    class="w-full px-4 py-2 rounded-md border-gray-300 focus:outline-none focus:border-blue-500"
                    required
                  />
                </div>
              </div>
              <div class="mb-4">
                <label for="name" class="block text-gray-700 font-medium mb-2">
                  Joueur1
                </label>
                <div class="mt-1 relative rounded-md shadow-sm">
                  <input
                    type="text"
                    id="Joueur1"
                    name="name"
                    placeholder="Enter the name"
                    class="w-full px-4 py-2 rounded-md border-gray-300 focus:outline-none focus:border-blue-500"
                    required
                  />
                </div>
              </div>
              <div class="mb-4">
                <label for="name" class="block text-gray-700 font-medium mb-2">
                  Joueur2
                </label>
                <div class="mt-1 relative rounded-md shadow-sm">
                  <input
                    type="text"
                    id="Joueur2"
                    name="name"
                    placeholder="Enter the name"
                    class="w-full px-4 py-2 rounded-md border-gray-300 focus:outline-none focus:border-blue-500"
                    required
                  />
                </div>
              </div>
              <div class="mb-4">
                <label for="name" class="block text-gray-700 font-medium mb-2">
                  Joueur3
                </label>
                <div class="mt-1 relative rounded-md shadow-sm">
                  <input
                    type="text"
                    id="Joueur3"
                    name="name"
                    placeholder="Enter the name"
                    class="w-full px-4 py-2 rounded-md border-gray-300 focus:outline-none focus:border-blue-500"
                    required
                  />
                </div>
              </div>
              <div class="mb-4">
                <label for="name" class="block text-gray-700 font-medium mb-2">
                  Joueur4
                </label>
                <div class="mt-1 relative rounded-md shadow-sm">
                  <input
                    type="text"
                    id="Joueur4"
                    name="name"
                    placeholder="Enter the name"
                    class="w-full px-4 py-2 rounded-md border-gray-300 focus:outline-none focus:border-blue-500"
                    required
                  />
                </div>
              </div>
              <div class="mb-4">
                <label for="name" class="block text-gray-700 font-medium mb-2">
                  Joueur5
                </label>
                <div class="mt-1 relative rounded-md shadow-sm">
                  <input
                    type="text"
                    id="Joueur5"
                    name="name"
                    placeholder="Enter the name"
                    class="w-full px-4 py-2 rounded-md border-gray-300 focus:outline-none focus:border-blue-500"
                    required
                  />
                </div>
              </div>

              <div class="flex items-center justify-between">
                <button
                  type="submit"
                  class="px-4 py-2 bg-blue-500 hover:bg-blue-600 text-white rounded-md focus:outline-none"
                >
                  Submit
                </button>
              </div>
            </form>
          </div>
        </div>
      </main>
    </>
  );
}
