import PlayersInfo from "@/components/tournament/players-info";
import TeamInfo from "@/components/tournament/team-info";
import Head from "next/head";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import tournamentSignRequestSchema from "@/validation/tournamentSignRequest";
import axios from "axios";

export default function TournamentSign() {
  const {
    register,
    handleSubmit,
    formState: { errors },
    reset,
  } = useForm({
    resolver: zodResolver(tournamentSignRequestSchema),
  });

  const onCreateTournament = async (data) => {
    const res = await axios.post("/api/sign-tournament", data);
    if (res.status === 201) {
      reset();
    }
  };

  return (
    <>
      <Head>
        <title>LA stadium</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="py-24">
        <h1 className="text-3xl py-4 font-bold mb-6 font text-center underline decoration-lime-500">
          Tournament Sign
        </h1>
        <form onSubmit={handleSubmit(onCreateTournament)}>
          <div className=" flex justify-center py-4 gap-16 h-fit">
            <TeamInfo register={register} errors={errors} />
            <PlayersInfo register={register} errors={errors} />
          </div>
        </form>
      </main>
    </>
  );
}
