import CategoryTraining from "@/components/tournament/category-training";
import Head from "next/head";

export default function Trainning() {
  return (
    <>
      <Head>
        <title>LA stadium</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div
          className=" hero flex items-center justify-center gap-12 h-screen"
          style={{
            backgroundImage: `url("/training.jpg")`,
          }}
        >
          <CategoryTraining
            category="A"
            age="5 ans a 8 ans"
            time="8h a 10h"
            tarif="35DT"
          />
          <CategoryTraining
            category="B"
            age="8 ans a 10 ans"
            time="8h a 10h"
            tarif="55DT"
          />
          <CategoryTraining
            category="C"
            age="10 ans a 12 ans"
            time="8h a 10h"
            tarif="65DT"
          />
        </div>
        <div>
          <div className="text-3xl font-bold mb-6 font text-center underline decoration-lime-500">
            pre-inscrire
          </div>
          <div className=" px-4 py-2 form-control w-full max-w-xs flex item-center  ">
            <label className="label">
              <span className="label-text">nom du parent</span>
              <span className="label-text-alt text-red-800 text-lg">*</span>
            </label>
            <input
              type="text"
              placeholder="Type here"
              className="input input-bordered w-full max-w-xs "
            />
          </div>
          <div className=" px-4 py-2 form-control w-full max-w-xs flex place-items-center">
            <label className="label">
              <span className="label-text">prenom du parent</span>
              <span className="label-text-alt text-red-800 text-lg">*</span>
            </label>
            <input
              type="text"
              placeholder="Type here"
              className="input input-bordered w-full max-w-xs"
            />
          </div>
          <div className=" px-4 py-2 form-control w-full max-w-xs flex place-items-center">
            <label className="label">
              <span className="label-text">numero de telephone</span>
              <span className="label-text-alt text-red-800 text-lg">*</span>
            </label>
            <input
              type="text"
              placeholder="Type here"
              className="input input-bordered w-full max-w-xs"
            />
          </div>
          <div className=" px-4 py-2 form-control w-full max-w-xs flex place-items-center">
            <label className="label">
              <span className="label-text">categorie</span>
              <span className="label-text-alt text-red-800 text-lg">*</span>
            </label>
            <input
              type="text"
              placeholder="Type here"
              className="input input-bordered w-full max-w-xs"
            />
          </div>
          <div className=" px-4 py-2 form-control w-full max-w-xs flex place-items-center">
            <label className="label">
              <span className="label-text">nom du joueur</span>
              <span className="label-text-alt text-red-800 text-lg">*</span>
            </label>
            <input
              type="text"
              placeholder="Type here"
              className="input input-bordered w-full max-w-xs"
            />
          </div>
          <div className=" px-4 py-2 form-control w-full max-w-xs flex place-items-center">
            <label className="label">
              <span className="label-text">prenom du joueur</span>
              <span className="label-text-alt text-red-800 text-lg">*</span>
            </label>
            <input
              type="text"
              placeholder="Type here"
              className="input input-bordered w-full max-w-xs"
            />
          </div>
        </div>
      </main>
    </>
  );
}
