import CategoryTraining from "@/components/tournament/category-training";
import Head from "next/head";

export default function Trainning() {
  return (
    <>
      <Head>
        <title>LA stadium</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div
          className=" hero flex items-center justify-center gap-12 h-screen"
          style={{
            backgroundImage: `url("/training.jpg")`,
          }}
        >
          <CategoryTraining
            category="A"
            age="5 ans a 8 ans"
            time="8h a 10h"
            tarif="35DT"
          />
          <CategoryTraining
            category="B"
            age="8 ans a 10 ans"
            time="8h a 10h"
            tarif="55DT"
          />
          <CategoryTraining
            category="C"
            age="10 ans a 12 ans"
            time="8h a 10h"
            tarif="65DT"
          />
        </div>
      </main>
    </>
  );
}
